### ISSUE TITLE
文字生成图片当文章是英文时，生成的图片中英文只占了一半的空间，满半行就换行了

### ISSUE THREAD

**Issue by jmh233** [liuyueyi/quick-media#100]
怎么才能将英文填充满一行？
![image](https://user-images.githubusercontent.com/58280952/180914578-8dbb0e36-f3c7-4445-956c-7d49ba1b4eae.png)

**Comment by liuyueyi** [comment]
https://github.com/liuyueyi/quick-media/blob/master/plugins/image-plugin/src/main/java/com/github/hui/quick/plugin/image/helper/CalculateHelper.java

![KPKTZR5WB$YT)06TJAKBELB](https://user-images.githubusercontent.com/5125892/180971110-8023ecfd-4775-490a-b5c3-a0b9c764dc26.png)
