### ISSUE TITLE
生成二维码报错

### ISSUE THREAD

**Issue by sod442995033** [liuyueyi/quick-media#110]
template might not exist or might not be accessible by any of the configured Template Resolvers
什么鬼？

**Comment by sod442995033** [comment]
是发起外部请求了吗？

**Comment by liuyueyi** [comment]
贴一下上下文，测试用例，堆栈信息
二维码本身不会发起外部请求，当你传入的资源为网络资源时，会下载对应的资源

**Comment by liuyueyi** [comment]
搜索了一下，业务代码中并没有这个提示，可能是引入的第三方jar包输出的，辛苦贴一下相关场景

**Comment by liuyueyi** [comment]
大佬，有后续么？
