### ISSUE TITLE
markdown转HTML支持中文?

### ISSUE THREAD

**Issue by 554291911** [liuyueyi/quick-media#21]
markdown转html,并不能支持中文,能否有解决办法?或者方便告知哪里改吗?

**Comment by liuyueyi** [comment]
这本机上测试可以支持中文，丢到服务器上跑的时候中文乱码，这一块还没定位到，待我研究一下

**Comment by liuyueyi** [comment]
不好意思，最近比较忙，这个问题已经定位到，主要是因为jdk不支持中文导致，解决方案如下

linux 系统:

```
#进入jdk安装目录 
cd /usr/local/jdk/jre/lib/fonts/

# 将宋体拷贝到目录下
cp simsun.ttf  /usr/local/jdk/jre/lib/fonts/

# 重启应用
```

宋体： [simsun.ttf](https://github.com/liuyueyi/quick-media/tree/master/common/src/main/resources/font/simsun.ttf) 已经打在包里了

**Comment by jazzhuang** [comment]
无法设置其它中文字体？
