### ISSUE TITLE
markdown-plugin 1.0 包没法 down 下来

### ISSUE THREAD

**Issue by evenson419** [liuyueyi/quick-media#26]
markdown-plugin 1.0 包没法 down 下来
![image](https://user-images.githubusercontent.com/35451163/40463623-db4d80d8-5f48-11e8-881e-e81af37b0d83.png)
![image](https://user-images.githubusercontent.com/35451163/40463637-ec0e96e6-5f48-11e8-9af1-2e9a2a382516.png)

**Comment by liuyueyi** [comment]
方便说一下您的使用方式么，是另外的项目依赖这个包无法引入，还是这个工程down下来之后引入有问题？

**Comment by liuyueyi** [comment]
```xml
<repositories>
    <repository>
        <id>yihui-maven-repo</id>
        <url>https://raw.githubusercontent.com/liuyueyi/maven-repository/master/repository</url>
    </repository>
</repositories>

<dependency>
    <groupId>com.github.hui.media</groupId>
    <artifactId>markdown-plugin</artifactId>
    <version>1.0</version>
</dependency>
```

添加源之后，试一下能下这个包么
