### ISSUE TITLE
依赖包下载不下来

### ISSUE THREAD

**Issue by Gitsifu** [liuyueyi/quick-media#27]

**Comment by liuyueyi** [comment]
pom文件中是否有添加下面

```xml
<repositories>
    <repository>
        <id>yihui-maven-repo</id>
        <url>https://raw.githubusercontent.com/liuyueyi/maven-repository/master/repository</url>
    </repository>
</repositories>
```

**Comment by Gitsifu** [comment]
添加了，还有就是最新版本是在哪里查看

**Comment by Gitsifu** [comment]
![image](https://user-images.githubusercontent.com/23445650/41599387-933d0e4a-7405-11e8-8ffa-8348129ef267.png)

下载不了

**Comment by liuyueyi** [comment]
- 重新deploy了一下，我本机测试可以拉下，您再试一下看下是否能下载
- 个人maven仓库基于github搭建的，可以到 [https://github.com/liuyueyi/maven-repository](https://github.com/liuyueyi/maven-repository) 查看相关的包，版本信息也可以在这个项目中查到
- 目前所有的版本都是1.0
- 如果依然有问题，麻烦回复一下，我再确认下是什么问题

**Comment by jinguifa** [comment]
这是我集成到我的项目pom文件
![1](https://user-images.githubusercontent.com/30431857/44458736-b8e28600-a639-11e8-9c4d-6797af2ae5c5.png)
![2](https://user-images.githubusercontent.com/30431857/44458760-cdbf1980-a639-11e8-84bd-b2713c47c13c.png)

**Comment by liuyueyi** [comment]
根据上面贴的图，需要引入的应该是 Qrcode-plugin， 完整的配置应该为

```xml
<repositories>
    <repository>
        <id>yihui-maven-repo</id>
        <url>https://raw.githubusercontent.com/liuyueyi/maven-repository/master/repository</url>
    </repository>
</repositories>

<dependencies>
<dependency>
    <groupId>com.github.hui.media</groupId>
    <artifactId>qrcode-plugin</artifactId>
    <version>1.0</version>
</dependency>
</dependencies>
```

在我本机和朋友的机器上测试，并没有什么问题，根据上面jar的下载路径，完整的url应该是:

```
## pom
https://raw.githubusercontent.com/liuyueyi/maven-repository/master/repository/com/github/hui/media/qrcode-plugin/1.0/qrcode-plugin-1.0.pom

## jar
https://raw.githubusercontent.com/liuyueyi/maven-repository/master/repository/com/github/hui/media/qrcode-plugin/1.0/qrcode-plugin-1.0.har

## 签名
https://raw.githubusercontent.com/liuyueyi/maven-repository/master/repository/com/github/hui/media/qrcode-plugin/1.0/qrcode-plugin-1.0.pom.sha1
```

上面的几个url，通过连接也是可以直接访问，请前面的老哥不妨试一下，如果依然有问题，请贴出下配置
