### ISSUE TITLE
二维码生成有遮罩

### ISSUE THREAD

**Issue by SimonHu1993** [liuyueyi/quick-media#37]
![code 2](https://user-images.githubusercontent.com/24569117/49141637-030e8e00-f332-11e8-850c-617e0b55ba98.jpg)

生成二维码时表层会有一层白色遮罩，用测试类测试时没问题。

**Comment by SimonHu1993** [comment]
![image](https://user-images.githubusercontent.com/24569117/49141676-1a4d7b80-f332-11e8-8858-26fbcb8ef0a6.png)
这是测试类

**Comment by liuyueyi** [comment]
看下是不是使用了透明度的参数，上面的表现形式就是透明度不是100%的情况

**Comment by liuyueyi** [comment]
https://zweb.hhui.top/#/qrcode/gen

我这个也是web调用的二维码生成实例，可以对比下使用参数

**Comment by SimonHu1993** [comment]
好的，我试试，就是仿照你的网站做的。应该是透明度问题，我看了你网站前台页面好像都是后台生成的模板，太6了

**Comment by SimonHu1993** [comment]
> https://zweb.hhui.top/#/qrcode/gen
> 
> 我这个也是web调用的二维码生成实例，可以对比下使用参数

看了下你网站传的参数和源码里的参数不一样，github源码中关于透明度只有一个背景图的，默认是0.85f，
但是我没有添加背景图，所以二维码的透明度是默认的- -不知道其他人有没有遇到。

**Comment by liuyueyi** [comment]
> > https://zweb.hhui.top/#/qrcode/gen
> > 我这个也是web调用的二维码生成实例，可以对比下使用参数
> 
> 看了下你网站传的参数和源码里的参数不一样，github源码中关于透明度只有一个背景图的，默认是0.85f，
> 但是我没有添加背景图，所以二维码的透明度是默认的- -不知道其他人有没有遇到。

我的web调用的后端对应的代码在这里，没有使用背景图的场景， 不传背景图时，不会使用到默认的.0.85f的透明度

https://github.com/liuyueyi/quick-media/blob/master/web/src/main/java/com/hust/hui/quickmedia/web/wxapi/qrcode/WxQrCodeAction.java

![image](https://user-images.githubusercontent.com/5125892/49191544-e6199f80-f3b1-11e8-97eb-b15f48c6e221.png)
![image](https://user-images.githubusercontent.com/5125892/49191621-2a0ca480-f3b2-11e8-8f9c-26c3311dc85c.png)

你看下你后端调用的地方，传入的背景图是不是非空，导致当成有背景图的方式进行处理了

---

此外，在有背景图的时候，默认设置二维码的透明度为0.85，主要是为了能够看到二维码后面的背景图

**Comment by SimonHu1993** [comment]
![image](https://user-images.githubusercontent.com/24569117/49197520-2422bd80-f3ca-11e8-8679-7708ab483e68.png)
不知道你这个取色板用的什么，传到后台直接就是完整的
![image](https://user-images.githubusercontent.com/24569117/49197567-44eb1300-f3ca-11e8-84a1-4cdaab877695.png)

我用的html原生属性

**Comment by SimonHu1993** [comment]
忘了，还有一点，后台把传过来的“#”要替换成“”不然就只有黑色了。
