### ISSUE TITLE
如何将html直接转换为jpg

### ISSUE THREAD

**Issue by linux2014linux** [liuyueyi/quick-media#42]
我看目前的test例子，都是将markdown转换为图片，我自己尝试了如下方式，但是转换出的图片只有两个null。

Html2ImageWrapper html2ImageWrapper = Html2ImageWrapper.of(".....").build();
html2ImageWrapper.asFile("/home/me/quick2image.jpg");

![image](https://user-images.githubusercontent.com/7777721/57187868-316b4780-6f28-11e9-822e-8a140735b34b.png)

**Comment by liuyueyi** [comment]
感谢反馈，已修复, 相关代码为: [fix #42](https://github.com/liuyueyi/quick-media/commit/4dddad34ad523becb4899ab92974d2b778ef05ab)

下面是测试截图

![image](https://user-images.githubusercontent.com/5125892/57189504-481e9800-6f42-11e9-9b5d-4d01655f5749.png)

**Comment by linux2014linux** [comment]
@liuyueyi 谢谢，已经可以正常运行了。
