### ISSUE TITLE
html转换为image时，css的样式无法渲染颜色等属性

### ISSUE THREAD

**Issue by linux2014linux** [liuyueyi/quick-media#43]
String htmlContent = "....";
        try {
            Html2ImageWrapper html2ImageWrapper = Html2ImageWrapper.of(htmlContent).build();
            html2ImageWrapper.asFile("/home/lt/quick2image.jpg");
        } catch (Exception e) {

        }

**Comment by liuyueyi** [comment]
提供一下完整的html

**Comment by linux2014linux** [comment]
@liuyueyi 我的html内容如下:
`<html xmlns="http://www.w3.org/1999/html">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width,initial-scale=1.0"/>
    <title>通知</title>
    <style type="text/css">
        ul, li {
            margin: 0;
            padding: 0;
        }

        body {
            margin: 30px 5%;
            background: #fff;
        }

        .html-fake {
            background: #fff;
            margin: 0 30px;
            overflow: hidden;
            font-family: "PingFang SC", "Hiragino Sans GB", "Microsoft YaHei", "Helvetica Neue", Helvetica, Arial, sans-serif;
            min-height: 320px;
            box-shadow: 0 0 8px 2px rgba(0, 0, 0, 0.08);
            border-radius: 3px;
        }

        .body-container {
            margin: 30px 30px 25px 37px;
        }

        .body-center .hi {
            font-size: 18px;
            color: #000000;
        }

        .body-center .text {
            padding-left: 20px;
            padding-top: 10px;
            font-size: 14px;
            color: #333;
        }

        .content .title {
            zoom: 1;
            padding-top: 20px;
            display: -webkit-box;
            display: -webkit-flex;
            display: flex;
        }

        .content .title::after {
            clear: both;
            content: ".";
            display: block;
            width: 0;
            height: 0;
            visibility: hidden;
        }

        .content .title .mark {
            display: inline-block;
            background: #fc9153;
            box-shadow: 0 0 13px 0 #fc9153;
            width: 2px;
            height: 14px;
            vertical-align: sub;
        }

        .content .title .name {
            color: black;
            padding-left: 4px;
            font-weight: bold;
        }

        .content .title .title-left {
            font-family: PingFangSC-Medium;
            font-size: 14px;
            color: #666;
            text-align: left;
        }

        .content .title .title-right {
            padding-left: 8px;
            -webkit-box-flex: 1;
            -webkit-flex: 1;
            flex: 1;
        }

        .content .title .title-right .line {
            border-bottom: 1px solid #ddd;
            height: 1px;
            width: 100%;
            position: relative;
            top: 9px;
        }

        .content .block ul {
            padding-left: 15px;
        }

        .content .lane-item ul {
            padding-left: 35px;
        }

        .content .task-item a {
            font-size: 14px;
            color: #3aabff;
            cursor: pointer;
            text-decoration: none;
        }

        .content .no-task .count span {
            display: inline-block;
            padding: 0 5px;
        }

        .body-btn .btn a {
            display: inline-block;
            height: 38px;
            line-height: 38px;
            padding: 0 16px;
            background: #fc9153;
            color: #fff;
            border-radius: 5px;
            text-decoration: none;
            font-size: 14px;
        }

        .body-bottom {
            text-align: center;
        }

        .body-bottom a {
            font-weight: bold;
            color: #666666;
            text-decoration: none;
        }

        .notice-hint {
            margin-top: 35px;
            color: #999;
            text-align: center;
            font-size: 14px;
        }

        .table-title {
            font-size: 14px;
            font-weight: bold;
            color: #777777;
            font-family: "PingFang SC", "Hiragino Sans GB", "Microsoft YaHei", "Helvetica Neue", Helvetica, Arial, sans-serif;
        }

        .table-body {
            font-size: 14px;
            color: #666666;
            font-family: "PingFang SC", "Hiragino Sans GB", "Microsoft YaHei", "Helvetica Neue", Helvetica, Arial, sans-serif;
        }

        /**
        table {
            border-collapse: collapse;
            border-spacing: 0;
        }
        td {
            padding-right: 12px;
            border: 1px solid #888888;
        }
        */
        td {
            padding-right: 12px;
            padding-bottom: 12px;
            width: 150px;
        }

        .positive {
            color: green;
        }

        .negative {
            color: red;
        }

    </style>
</head>
<body>
<div class="html-fake">
    <div class="body-container">
        <div class="body-center">
            <div class="hi">
                Alg:<br/>
            </div>
            <div class="text">
                您好！您所订阅的数据报表信息如下.<br/>
            </div>

            <div class="content">
                <div class="title">
                    <div class="title-left">
                        <span class="mark"></span>
                        <span class="name">消费数据</span>
                    </div>
                    <div class="title-right">
                        <div class="line"></div>
                    </div>
                </div>

                <div class="block">
                    <table>
                        <thead class="table-title">
                        <td>指标</td>
                        <td>group_a</td>
                        <td>group_b</td>
                        </thead>
                        <tbody class="table-body">
                        <tr>
                            <td>Index_A</td>
                            <td>0.92264</td>
                            <td>0.73658<span class="negative">(-0.00069, -0.07500%)&nbsp;&#8595;</span></td>
                        </tr>
                        <tr>
                            <td>Index_B</td>
                            <td>0.92195</td>
                            <td>0.73584<span class="negative">(-0.00074, -0.10000%)&nbsp;&#8595;</span></td>
                        </tr>
                        <tr>
                            <td>Index_C</td>
                            <td>1617.14677</td>
                            <td>1636.57827<span class="positive">(19.4315, 1.20200%)&nbsp;&#8593;</span></td>
                        </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
</body>
</html>
`

**Comment by linux2014linux** [comment]
`
<html xmlns="http://www.w3.org/1999/html">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width,initial-scale=1.0"/>
    <title>通知</title>
    <style type="text/css">
        ul, li {
            margin: 0;
            padding: 0;
        }

        body {
            margin: 30px 5%;
            background: #fff;
        }

        .html-fake {
            background: #fff;
            margin: 0 30px;
            overflow: hidden;
            font-family: "PingFang SC", "Hiragino Sans GB", "Microsoft YaHei", "Helvetica Neue", Helvetica, Arial, sans-serif;
            min-height: 320px;
            box-shadow: 0 0 8px 2px rgba(0, 0, 0, 0.08);
            border-radius: 3px;
        }

        .body-container {
            margin: 30px 30px 25px 37px;
        }

        .body-center .hi {
            font-size: 18px;
            color: #000000;
        }

        .body-center .text {
            padding-left: 20px;
            padding-top: 10px;
            font-size: 14px;
            color: #333;
        }

        .content .title {
            zoom: 1;
            padding-top: 20px;
            display: -webkit-box;
            display: -webkit-flex;
            display: flex;
        }

        .content .title::after {
            clear: both;
            content: ".";
            display: block;
            width: 0;
            height: 0;
            visibility: hidden;
        }

        .content .title .mark {
            display: inline-block;
            background: #fc9153;
            box-shadow: 0 0 13px 0 #fc9153;
            width: 2px;
            height: 14px;
            vertical-align: sub;
        }

        .content .title .name {
            color: black;
            padding-left: 4px;
            font-weight: bold;
        }

        .content .title .title-left {
            font-family: PingFangSC-Medium;
            font-size: 14px;
            color: #666;
            text-align: left;
        }

        .content .title .title-right {
            padding-left: 8px;
            -webkit-box-flex: 1;
            -webkit-flex: 1;
            flex: 1;
        }

        .content .title .title-right .line {
            border-bottom: 1px solid #ddd;
            height: 1px;
            width: 100%;
            position: relative;
            top: 9px;
        }

        .content .block ul {
            padding-left: 15px;
        }

        .content .lane-item ul {
            padding-left: 35px;
        }

        .content .task-item a {
            font-size: 14px;
            color: #3aabff;
            cursor: pointer;
            text-decoration: none;
        }

        .content .no-task .count span {
            display: inline-block;
            padding: 0 5px;
        }

        .body-btn .btn a {
            display: inline-block;
            height: 38px;
            line-height: 38px;
            padding: 0 16px;
            background: #fc9153;
            color: #fff;
            border-radius: 5px;
            text-decoration: none;
            font-size: 14px;
        }

        .body-bottom {
            text-align: center;
        }

        .body-bottom a {
            font-weight: bold;
            color: #666666;
            text-decoration: none;
        }

        .notice-hint {
            margin-top: 35px;
            color: #999;
            text-align: center;
            font-size: 14px;
        }

        .table-title {
            font-size: 14px;
            font-weight: bold;
            color: #777777;
            font-family: "PingFang SC", "Hiragino Sans GB", "Microsoft YaHei", "Helvetica Neue", Helvetica, Arial, sans-serif;
        }

        .table-body {
            font-size: 14px;
            color: #666666;
            font-family: "PingFang SC", "Hiragino Sans GB", "Microsoft YaHei", "Helvetica Neue", Helvetica, Arial, sans-serif;
        }
        td {
            padding-right: 12px;
            padding-bottom: 12px;
            width: 150px;
        }

        .positive {
            color: green;
        }

        .negative {
            color: red;
        }

    </style>
</head>
<body>
<div class="html-fake">
    <div class="body-container">
        <div class="body-center">
            <div class="hi">
                Alg:<br/>
            </div>
            <div class="text">
                您好！您所订阅的数据报表信息如下.<br/>
            </div>

            <div class="content">
                <div class="title">
                    <div class="title-left">
                        <span class="mark"></span>
                        <span class="name">消费数据</span>
                    </div>
                    <div class="title-right">
                        <div class="line"></div>
                    </div>
                </div>

                <div class="block">
                    <table>
                        <thead class="table-title">
                        <td>指标</td>
                        <td>group_a</td>
                        <td>group_b</td>
                        </thead>
                        <tbody class="table-body">
                        <tr>
                            <td>Index_A</td>
                            <td>0.92264</td>
                            <td>0.73658<span class="negative">(-0.00069, -0.07500%)&nbsp;&#8595;</span></td>
                        </tr>
                        <tr>
                            <td>Index_B</td>
                            <td>0.92195</td>
                            <td>0.73584<span class="negative">(-0.00074, -0.10000%)&nbsp;&#8595;</span></td>
                        </tr>
                        <tr>
                            <td>Index_C</td>
                            <td>1617.14677</td>
                            <td>1636.57827<span class="positive">(19.4315, 1.20200%)&nbsp;&#8593;</span></td>
                        </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
</body>
</html>

`

**Comment by liuyueyi** [comment]
已修复，使用姿势可以参考: [https://github.com/liuyueyi/quick-media/blob/master/plugins/markdown-plugin/src/test/java/com/github/hui/quick/plugin/test/Html2ImgTest.java](https://github.com/liuyueyi/quick-media/blob/master/plugins/markdown-plugin/src/test/java/com/github/hui/quick/plugin/test/Html2ImgTest.java)

![image](https://user-images.githubusercontent.com/5125892/58018479-89fc3080-7b35-11e9-8ce1-ce547f3c9144.png)

**Comment by linux2014linux** [comment]
@liuyueyi 我在我本地转换出的图片质量有点差，我和wkhtml2image对比效果如下，这个可以调整吗？
![group_classify_dup_block](https://user-images.githubusercontent.com/7777721/58088951-57fed300-7bf6-11e9-8142-3ca69151842c.png)

**Comment by liuyueyi** [comment]
> @liuyueyi 我在我本地转换出的图片质量有点差，我和wkhtml2image对比效果如下，这个可以调整吗？
> ![group_classify_dup_block](https://user-images.githubusercontent.com/7777721/58088951-57fed300-7bf6-11e9-8142-3ca69151842c.png)
> 包括整个样式也有点不同。

看着像是字体的原因导致的，左边应该是用的宋体，右边是苹方吧

**Comment by linux2014linux** [comment]
@liuyueyi 但是你看两边的风格都是不同的，我对比了你转换出的图片和wkhtml2image转换出的图片，图片的样式是有明显差异的。
a.quick-media无法自动适配html的大小；
b.quick-media转换出的图片没有凸起的样式；
c.在"消费指标"处的样式也是有明显差异的；
我怀疑是因为quick-media和wkhtml2image所使用的渲染引擎不同导致的。quick-media可以切换渲染引擎吗？可以的话，我可以试试。

**Comment by liuyueyi** [comment]
渲染引擎不一样，quick-media 依赖的是原生jdk进行的；wkhtml2image这个c++实现的吧

quick-media支持基于phantomjs方式的html渲染，不过性能有点感人

**Comment by linux2014linux** [comment]
@liuyueyi 好吧，感谢了！手动点赞！
