### ISSUE TITLE
二维码输出JPG图片的时候，需要使用BufferedImage.TYPE_INT_RGB

### ISSUE THREAD

**Issue by totemtec** [liuyueyi/quick-media#45]
JDK8测试的时候，使用BufferedImage.TYPE_INT_**A**RGB的话，直接输出一个全黑的图片

**Comment by liuyueyi** [comment]
麻烦给一个可以复现的测试case

**Comment by totemtec** [comment]
public static void testGenerateQrcode() {
        String content = "https://liuyueyi.github.io/hexblog/2018/03/23/mysql/";
        int size = 300;
        try {
            BufferedImage img = QrCodeGenWrapper.of(content)
                    .setW(size)
                    .setH(size)
                    .setPicType("png") 
                    .asBufferedImage();
            ImageIO.write(img, "jpg", new File("/Users/majianglin/Desktop/style.jpg")); //这句不能使用"jpg"
        } catch (IOException e) {
            e.printStackTrace();
        } catch (WriterException e) {
            e.printStackTrace();
        }
    }

有可能是ImageIO的锅，ImageIO.write里的formatName使用"jpg"，怎么都出不来正常图片，只有全黑的图
而把代码里所有的ARGB改为RGB就可以出来
跟我用都图片关系也不大，尝试找了好几种工具生成的图片
系统是Mac10.13

另外Logo使用透明背景的PNG图片，setLogoBgColor(Color.TRANSLUCENT)，目的是想让Logo把底下的二维码图案也能透过来。不过效果好像不对，绘制二维码和绘制logo时，颜色好像是混合的，期望logo有颜色的地方覆盖二维码，透明的地方露出二维码

**Comment by liuyueyi** [comment]
上面的case中，希望输出是png格式的图片，这个时候输出图片的时候，指定输出类型也应该为png，而不是jpg； 因为jpg图片没有alpha通道，不带透明度，而png格式的图片是有透明度的，所以这两个格式最好不要混用

- 希望得到jpg格式图片，`setPicType ` 传jpg； 最后写到一个jpg格式的图片文件
- 希望得到png格式图片，`setPicType ` 传png； 最后写到一个png格式的图片文件

**Comment by totemtec** [comment]
picType传jpg也是一样的，试过了

**Comment by liuyueyi** [comment]
> picType传jpg也是一样的，试过了

当指定的二维码图片格式和最后保存为图片文件的格式一致的时候，是没有问题的

下面这个是输出png格式的图片：

![image](https://user-images.githubusercontent.com/5125892/59600525-f4ec5780-9133-11e9-9ddc-0b855d871924.png)

下面这个是输出jpg格式的图片

![image](https://user-images.githubusercontent.com/5125892/59600571-22d19c00-9134-11e9-829b-ba67ad820d73.png)

此外，不指定logo的样式和边框的时候，logo透明的地方会显示二维码相关信息，如下图的胡萝卜周围显示的是二维码信息

```java
@Test
    public void testGenColorCode() {
        String msg = "https://liuyueyi.github.io/hexblog/";
        // 根据本地文件生成待logo的二维码， 重新着色位置探测图像
        try {
            String logo = "lobo_logo.png";
            String bg = "bg.png";
            BufferedImage img = QrCodeGenWrapper.of(msg)
                    .setW(500)
                    .setDrawPreColor(0xff002fa7) // 宝石蓝
                    .setDetectOutColor(0xff00ff00)
                    .setDetectInColor(0xffff0000)
                    .setPadding(1)
                    .setErrorCorrection(ErrorCorrectionLevel.H)
                    .setLogo(logo)
//                    .setLogoStyle(QrCodeOptions.LogoStyle.ROUND)
//                    .setLogoBgColor(0xff000000)
                    .setBgImg(bg)
                    .setDrawStyle(QrCodeOptions.DrawStyle.IMAGE.name())
                    .setDrawImg("xhrSize4.jpg")
                    .setPicType("jpg")
                    .asBufferedImage();


            ByteArrayOutputStream outputStream = new ByteArrayOutputStream();
            ImageIO.write(img, "jpg", outputStream);
            String img64 = Base64Util.encode(outputStream);
            System.out.println("<img src=\"data:image/png;base64," + img64 + "\" />");
        } catch (Exception e) {
            System.out.println("cmvreate qrcode error! e: " + e);
            Assert.assertTrue(false);
        }
    }
```
![image](https://user-images.githubusercontent.com/5125892/59601031-742e5b00-9135-11e9-9f9d-f029d1dd3d2a.png)
