### ISSUE TITLE
setFontColor并不能work

### ISSUE THREAD

**Issue by jazzhuang** [liuyueyi/quick-media#61]
https://github.com/liuyueyi/quick-media/blob/31c4e904db9429105415cad2c2a91f4de84f8e60/plugins/markdown-plugin/src/main/java/com/github/hui/quick/plugin/md/Html2ImageWrapper.java#L208

**Comment by liuyueyi** [comment]
fontcolor 已修复

![image](https://user-images.githubusercontent.com/5125892/62939063-f4ee9800-be02-11e9-8b3a-de2ab7863318.png)
