### ISSUE TITLE
带logo的二维码无法识别

### ISSUE THREAD

**Issue by horsen689** [liuyueyi/quick-media#65]
就按文档引入了jar包，然后copy了代码写了个测试类，对应的logo图片路径该成了本地的路径
二维码是生成了，但是用UC/QQ/其他软件挨个扫了遍，都无法识别
然后我怀疑是不是我的图片问题，就去用了百度来的图片，发现也识别不了
是不是有什么bug？

另外说一句：作者的东西做的很赞，至少用起来蛮爽的
 

**<dependency>
  <groupId>com.github.hui.media</groupId>
  <artifactId>qrcode-plugin</artifactId>
  <version>2.2</version>
</dependency>**

> //        String logo = "/Users/horsen/Downloads/ywlogo.jpg";
>         String logo = "http://img1.imgtn.bdimg.com/it/u=2018939532,1617516463&fm=26&gp=0.jpg";
>         String msg = "https://liuyueyi.github.io/hexblog/2018/03/23/mysql之锁与事务详解/";
>         int size = 500;
>         try {
> 
>             boolean ans = QrCodeGenWrapper.of(msg)
>                     .setW(300)
>                     .setDrawPreColor(0xff0000ff)
>                     .setDrawBgColor(0xffffffff)
>                     .setDetectOutColor(0xff00FF00)
>                     .setDetectInColor(0xffff0000)
>                     .setPadding(1)
>                     .setLogo(logo)
>                     .setLogoRate(12)
>                     .setLogoStyle(QrCodeOptions.LogoStyle.ROUND)
>                     .setLogoBorder(true)
>                     .setLogoBgColor(Color.GREEN)
>                     .setBgOpacity(0.8f)
>                     .setBgStyle(QrCodeOptions.BgImgStyle.FILL)
>                     .setBgStartX(108)
>                     .setBgStartY(40)
>                     .asFile("/Users/horsen/Downloads/yyy.png");
>         } catch (IOException e) {
>             e.printStackTrace();
>         } catch (WriterException e) {
>             e.printStackTrace();
>         }

**Comment by liuyueyi** [comment]
下面是我根据提供的代码生成的，可以扫描；麻烦提供一下您这边生成的图片

![image](https://user-images.githubusercontent.com/5125892/68915751-5de90180-079e-11ea-8358-b6f2d2024381.png)

**Comment by horsen689** [comment]
> 下面是我根据提供的代码生成的，可以扫描；麻烦提供一下您这边生成的图片
> 
> ![image](https://user-images.githubusercontent.com/5125892/68915751-5de90180-079e-11ea-8358-b6f2d2024381.png)

我这边后来可以了（没改过任何代码），具体原因不是很清楚

谢谢您的回复哈，很喜欢你做的这些媒体工具，thx

顺便请问一下，我用html转成图片也存在一些问题，如果有时间可以请你看一下嘛：https://github.com/liuyueyi/quick-media/issues/66

**Comment by horsen689** [comment]
> > 下面是我根据提供的代码生成的，可以扫描；麻烦提供一下您这边生成的图片
> > ![image](https://user-images.githubusercontent.com/5125892/68915751-5de90180-079e-11ea-8358-b6f2d2024381.png)
> 
> 我这边后来可以了（没改过任何代码），具体原因不是很清楚
> 
> 谢谢您的回复哈，很喜欢你做的这些媒体工具，thx
> 
> 顺便请问一下，我用html转成图片也存在一些问题，如果有时间可以请你看一下嘛：#66

已经解决  是我自己写的html的问题
