### ISSUE TITLE
依赖引入失败问题

### ISSUE THREAD

**Issue by CheungChingYin** [liuyueyi/quick-media#67]
老哥，你的repository依赖 https://raw.githubusercontent.com/liuyueyi/maven-repository/master/repository 请问是什么问题？
![image](https://user-images.githubusercontent.com/20316736/71363479-44747a00-25d4-11ea-9330-1dc745d1d52c.png)

**Comment by liuyueyi** [comment]
是不是被墙了， 直接访问下面看能访问么

https://raw.githubusercontent.com/liuyueyi/maven-repository/master/repository/com/github/hui/media/qrcode-plugin/2.2/qrcode-plugin-2.2.pom

**Comment by CheungChingYin** [comment]
昨天我是开着小飞机来拉的，可能是网络抽风了，今天再拉一次突然就行了，谢谢您的回复。也很感激您的开源
