### ISSUE TITLE
生成的二维码中添加logo，如果logo的图形为长方形，则会变形

### ISSUE THREAD

**Issue by ldk-2512** [liuyueyi/quick-media#81]
原图logo
![logo](https://user-images.githubusercontent.com/73157953/96818783-b87de980-1454-11eb-8660-4701b19f86b9.jpg)

生成的二维码
![dqr6](https://user-images.githubusercontent.com/73157953/96818770-af8d1800-1454-11eb-8467-87185208344d.png)

**Comment by ldk-2512** [comment]
![image](https://user-images.githubusercontent.com/73157953/96818802-ca5f8c80-1454-11eb-993a-a52a2f074aa1.png)
原因分析：
在计算logo的宽高时， 如果logo原图的宽比 通过logo比例计算的的宽大时，使用的是计算的， logo原图的高则比计算的高小，所以用的原图的高
这就有导致生成的logo 的宽用的通过logo比例计算的，  高却用原图的，所以会导致生成出来的二维码中的logo变形

解决方案：
在计算logo的长宽时， 如果原logo的宽比 通过logo比例计算的的宽大时，使用的是计算的，通过logo比例计算的宽和原logo的宽比值， 来计算logo的高，
反正宽用原图的，  高用计算的，  通过logo比例计算的高和原logo的高比值， 来计算logo的宽，

**Comment by ldk-2512** [comment]
![1603336171(1)](https://user-images.githubusercontent.com/73157953/96819812-1c091680-1457-11eb-893d-b25aec868b9d.jpg)

**Comment by liuyueyi** [comment]
收到，感谢指正

**Comment by liuyueyi** [comment]
已处理，最近事情有点多，耽误了
