### ISSUE TITLE
调用生成二维码的插件时，报错，java.lang.ClassNotFoundException: org.apache.commons.lang.BooleanUtils

### ISSUE THREAD

**Issue by ldk-2512** [liuyueyi/quick-media#82]
![1603767534(1)](https://user-images.githubusercontent.com/73157953/97251768-79300e00-1843-11eb-9ecd-95622eb13002.jpg)
但是我本地是有这个包的
![1603767599(1)](https://user-images.githubusercontent.com/73157953/97251812-94028280-1843-11eb-926a-3e7c5adf898f.jpg)

**Comment by ldk-2512** [comment]
个人建议：
这个插件是个公共插件， 建议一些第三方的依赖尽量不用，  自己内部做支持

**Comment by liuyueyi** [comment]
jar包冲突，打一下依赖树

**Comment by ldk-2512** [comment]
![1603781853(1)](https://user-images.githubusercontent.com/73157953/97267216-c4a6e400-1864-11eb-9fed-2b7734736b72.jpg)
mei没有common-lang的包呀

**Comment by ldk-2512** [comment]
![1603782184(1)](https://user-images.githubusercontent.com/73157953/97267702-89f17b80-1865-11eb-9d40-96557b37ac6e.jpg)
是不是应该把scope去掉啊， 不然打包的时候，  打不进去吧

**Comment by liuyueyi** [comment]
一般这个jar包属于很常用的依赖，为了避免这个插件引入的包和使用方的冲突，所以使用的是 provided
