### ISSUE TITLE
二维码触发去白边的逻辑，导致二维码缩放不正确。

### ISSUE THREAD

**Issue by yoyo0403** [liuyueyi/quick-media#88]
我使用的版本是：
        <dependency>
            <groupId>com.github.liuyueyi.media</groupId>
            <artifactId>qrcode-plugin</artifactId>
            <version>2.5.5</version>
        </dependency>
在生成中心带 logo 的二维码时，如果二维码本身内容较多，触发了去白边的逻辑。在缩放处理后。二维码渲染有问题，效果如下：
![lala](https://user-images.githubusercontent.com/23547860/109623045-b7ce3000-7b77-11eb-99d9-4a5a844f6c19.png)
在网上看到你以前的一个贴子（https://my.oschina.net/u/566591/blog/872770），看到了下面的代码：
![微信截图_20210302163458](https://user-images.githubusercontent.com/23547860/109623363-0a0f5100-7b78-11eb-8e57-6a9007354102.png)
看了一下源码，现在代码是这样的：
com.github.hui.quick.plugin.base.GraphicUtil#createImg(int, int, int, int, java.awt.image.BufferedImage, java.awt.Color)
我现在改成了下面这样。至少目前解决了我目前的问题。因为我这里网络原因看不了历史变动所以不太清楚，作者为什么去掉了该逻辑。这里询问一下原因。另附一个demo
![微信截图_20210302164616](https://user-images.githubusercontent.com/23547860/109623995-ab96a280-7b78-11eb-8530-bc5a83931063.png)

[QrCodeGenerator.zip](https://github.com/liuyueyi/quick-media/files/6067398/QrCodeGenerator.zip)

**Comment by liuyueyi** [comment]
2.6.0 已修复这个问题
