### ISSUE TITLE
可以如何在生成的二维码中增加文字信息？

### ISSUE THREAD

**Issue by ss5656** [liuyueyi/quick-media#90]
如题，在博主的项目中可以在生成的二维码中增加问题信息吗？

**Comment by liuyueyi** [comment]
没太明白

**Comment by ss5656** [comment]
就是怎么在二维码图片上增加一些文字？

**Comment by liuyueyi** [comment]
> 就是怎么在二维码图片上增加一些文字？

这种么? 
![image](https://user-images.githubusercontent.com/5125892/116558464-0a3a8b80-a932-11eb-96da-6c6e3b58da3d.png)

**Comment by ss5656** [comment]
恩  是的
好聪明！

**Comment by liuyueyi** [comment]
> 恩 是的
> 好聪明！

可以参考下示例教程

https://liuyueyi.github.io/quick-media/#/%E6%8F%92%E4%BB%B6/%E4%BA%8C%E7%BB%B4%E7%A0%81/%E4%BA%8C%E7%BB%B4%E7%A0%81%E6%8F%92%E4%BB%B6%E4%BD%BF%E7%94%A8%E6%89%8B%E5%86%8C?id=i-%e5%89%8d%e7%bd%ae%e5%9b%be
