### ISSUE TITLE
能否支持颜色渐变

### ISSUE THREAD

**Issue by cuihj** [liuyueyi/quick-media#99]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by liuyueyi** [comment]
具体描述下，哪个插件支持颜色渐变，最好给一个示例

**Comment by cuihj** [comment]
like  
![image](https://user-images.githubusercontent.com/6811333/196074530-cb0a10d6-2e75-418a-bf8b-7973bd525839.png)

**Comment by liuyueyi** [comment]
现在就支持通过背景图的方式来实现这个效果；即弄一个蓝绿三拼的颜色背景图，然后指定 `BgStyle = QrCodeOptions.BgImgStyle.PENETRATE` 即可实现类似的效果

- [2.x示例教程](https://hhui.top/quick/quick-media/qrcode/2.x%E4%BD%BF%E7%94%A8%E5%AE%9E%E4%BE%8B/#d-%E6%8C%87%E5%AE%9A%E8%83%8C%E6%99%AF%E5%9B%BE)
- 3.x示例，教程还没写完，直接看源码吧： [QrImgBgGenTest#penetrateBg](https://github.com/liuyueyi/quick-media/blob/master/plugins/qrcode-plugin/src/test/java/com/github/hui/quick/plugin/test/v3/img/QrImgBgGenTest.java)

实际效果图如：

![bg_penetrate](https://user-images.githubusercontent.com/5125892/196077632-301953d9-c7c7-40d4-b820-3b4aee114875.png)

**Comment by cuihj** [comment]
谢谢
